<a href="https://colab.research.google.com/github/DataZone123/numpy_yt/blob/main/Advanced_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy--->Advanced Indexing



*   If we want to access multiple elements, which are not in order
(arbitrary elements) of 1D,2D and N-D arrays we must use the concept of Advanced Indexing.
*   If we want access the elements based on some condition  then we can't use basic indexing and Basic Slicing Operations. To fullfill such type of requirements we use advanced Indexing.


## Accessing Multiple Arbitrary Elements ---1D :

 Syntax:-          ndarrayname [ x ]

Here 'x' can be either ndarray or list which represents required indexes of arbitrary elements.

In [1]:
lst = [10,20,30,40,50,60,70,80,90]
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [3]:
import numpy as np
a = np.array(lst)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

here ww want to fetch only 10,30, and 80 elemnt from this array.

so,we should know ther index of ther elemnt
which are 0, 2,7

In [4]:
lst = [0,2,7]

In [5]:
a[lst]

array([10, 30, 80])

In [6]:
a[[0,2,7]]

array([10, 30, 80])

In [7]:
lst

[0, 2, 7]

In [8]:
arr1 = np.array(lst)
arr1

array([0, 2, 7])

In [9]:
a[arr1]

array([10, 30, 80])

## Accessing Multiple Arbitrary Elements ---2D :

 Syntax:-          ndarrayname [ [row indexes],[column indexes] ]



In [11]:
import numpy as np

arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
arr2d.ndim

2

In [13]:
arr2d.shape

(4, 4)

Q:-Access principal diagonal elemnts (1,6,11,16)

In [14]:
arr2d[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [15]:
arr2d[[1,3],[0,2]]

array([ 5, 15])

## Accessing Multiple Arbitrary Elements ---3D :

 Syntax:-          ndarrayname [ [Index of 2dmatrix],[row indexes],[column indexes] ]



In [16]:
import numpy as np
l1 =[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]
arr3d = np.array(l1)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [17]:
arr3d.ndim

3

In [18]:
arr3d.shape

(2, 3, 4)

Q:- aceess elements 1,14,24

In [19]:
arr3d[[0,1,1],[0,0,2],[0,1,3]]

array([ 1, 14, 24])

In [25]:

x = (0,1,1)
y = (0,0,2)
z = (0,1,3)

arr3d[x,y,z]

array([ 1, 14, 24])

Q:- access elemnts 10,22


In [26]:
arr3d[[0,1],[2,2],[1,1]]

array([10, 22])

## Accessing Multiple Arbitrary Elements ---4D :



In [27]:
a = np.array([10,20,30,40,50,60,70,80,15,25,35,45,55,65,75,85])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 15, 25, 35, 45, 55, 65, 75, 85])

In [28]:
a.ndim

1

In [29]:
a.shape

(16,)

In [30]:
a.shape = (2,2,2,2)

In [31]:
a

array([[[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]],


       [[[15, 25],
         [35, 45]],

        [[55, 65],
         [75, 85]]]])

In [32]:
a.ndim

4

In [33]:
a.shape

(2, 2, 2, 2)

In [34]:
a[0][0][0][0]

10

In [35]:
a[[0,1],[0,0],[0,1],[0,1]]

array([10, 45])

Q: aceess 60,65,15 and 25?
