<a href="https://colab.research.google.com/github/DataZone123/numpy_yt/blob/main/Advanced_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy--->Advanced Indexing



*   If we want to access multiple elements, which are not in order
(arbitrary elements) of 1D,2D and N-D arrays we must use the concept of Advanced Indexing.
*   If we want access the elements based on some condition  then we can't use basic indexing and Basic Slicing Operations. To fullfill such type of requirements we use advanced Indexing.


## Accessing Multiple Arbitrary Elements ---1D :

 Syntax:-          ndarrayname [ x ]

Here 'x' can be either ndarray or list which represents required indexes of arbitrary elements.

In [1]:
lst =[10,20,30,30,40,50,60,70,80]
lst

[10, 20, 30, 30, 40, 50, 60, 70, 80]

In [2]:
import numpy as np
a = np.array(lst)

In [3]:
a

array([10, 20, 30, 30, 40, 50, 60, 70, 80])

requirement are 10,30,60

we will check the index of above elements

which are 0,2 and 6

In [8]:
ind =[0,2,6]

In [5]:
ind

[0, 2, 6]

In [6]:
indexes = np.array(ind)
indexes

array([0, 2, 6])

In [7]:
a[indexes]

array([10, 30, 60])

In [10]:
a[0,2,6]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [11]:
a[ind]

array([10, 30, 60])

## Accessing Multiple Arbitrary Elements ---2D :

 Syntax:-          ndarrayname [ [row indexes],[column indesxes]]



In [13]:
import numpy as np

b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Q1 --> access the principal diagonal elements(1,6,11,16)

In [15]:
b[ [0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

=> When the abobe statement is executed ,The PVM takes internally as
b[(0,0),(1,1),(2,2),(3,3)]

Q2:- acces the elemnts 7,15?


In [16]:
b[[1,3],[2,2]]

array([ 7, 15])

## Accessing Multiple Arbitrary Elements ---3D :

 Syntax:-     ndarrayname [[Indexes of 2d matrix], [row indexes],[column indesxes]]

In [18]:
l1 = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

In [19]:
l1

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [21]:
mat3d = np.array(l1)

In [22]:
mat3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [24]:
mat3d.ndim

3

In [25]:
mat3d.shape

(2, 3, 4)

Q:- access elemnts 1,14,24

In [26]:
mat3d[[0,1,1],[0,0,2],[0,1,3]]

array([ 1, 14, 24])

Q:- acess elements 11,23?

In [27]:
mat3d[[0,1],[2,2],[2,2]]

array([11, 23])

In [28]:
matind = (0,1)
rowind = (2,2)
colind =(2,2)

In [29]:
mat3d[matind,rowind,colind]

array([11, 23])

## 4d Array

In [35]:
a = np.array([10,20,30,40,50,60,70,80,15,25,35,45,55,65,75,85])
a.shape

(16,)

In [36]:
a.shape =(2,2,2,2)

In [37]:
a

array([[[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]],


       [[[15, 25],
         [35, 45]],

        [[55, 65],
         [75, 85]]]])

In [39]:
a.ndim

4

In [40]:
a[0][0][0][0]

10

access 10 and 40?

In [41]:
a[[0,0],[0,0],[0,1],[0,1]]

array([10, 40])

Q:access 60,55 and 15  from a?