<a href="https://colab.research.google.com/github/DataZone123/numpy_yt/blob/main/Indexing_slicing_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Indexing and Slicing Operations on Numpy(1D,2D and 3D) array


**1D Arrays Slicing:**

Syntax:-   1dndrrayobj[begin:end:step]

Example:-
>>> a=np.array([10,20,30,40,50,60,70])


**2D Arrays Slicing:**

Syntax:- ndrrayobj[i,j]
	here 'i' represents  Row Index
	here 'j' represents Column Index

Syntax:-       2dndrrayobj[Row Index, Column Index]

Syntax:-       2dndrrayobj[begin:end:step, begin:end:step]


Example:-

>>> a=np.array([[10,20,30],[40,50,60]])


**3D Arrays Slicing**

Syntax:-       3dndrrayobj[i,j,k]

	here 'i' represents Which 2D matrix ( Matrix Number-->0 1 2 3 4 5...... )
	here 'j' represents which Rows in that 2D matrix
	here 'k' represents which Columns in that 2D matrix

												(OR)
Syntax:-       3dndrrayobj[ Matrix Index, Row Index, Column Index ]

												(OR)

Syntax:-       3dndrrayobj[begin:end:step, begin:end:step, begin:end:step ]

Examples:

>>> lst=[ [ [1,2,3],[4,5,6],[7,8,9] ],[ [13,14,15],[16,17,18],[19,20,21] ] ]

In [13]:
s ="python"
print(s,type(s))

python <class 'str'>


In [3]:
s[0]

'p'

In [4]:
s[1]

'y'

In [5]:
s[2]

't'

In [6]:
s[3]

'h'

In [7]:
s[4]

'o'

In [8]:
s[5]

'n'

In [9]:
s[-6]

'p'

In [10]:
s[-1]

'n'

In [11]:
s[0:2]

'py'

In [14]:
s[0:1]

'p'

### 1D array slicing

In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70])

In [17]:
a

array([10, 20, 30, 40, 50, 60, 70])

In [18]:
a.ndim

1

In [19]:
a[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [20]:
a[::]

array([10, 20, 30, 40, 50, 60, 70])

## 2D array slicing

In [23]:
a=np.array([[10,20,30],[40,50,60]])

In [24]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
a.ndim

2

In [26]:
a[0,0]

10

In [27]:
a[0,0:1]

array([10])

In [28]:
a[0,1:2]

array([20])

In [29]:
a[0,2:3]

array([30])

In [30]:
a[1,2:3]

array([60])

## 3D array slicing


In [33]:
lst=[ [ [1,2,3],[4,5,6],[7,8,9] ],[ [13,14,15],[16,17,18],[19,20,21] ] ]

In [34]:
lst

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[13, 14, 15], [16, 17, 18], [19, 20, 21]]]

In [35]:
arr1 = np.array(lst)

In [36]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [37]:
arr1.ndim

3

In [40]:
# syntax = 3darry[i,j,k]

In [41]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [42]:
arr1[:,:,0:1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[13],
        [16],
        [19]]])

In [43]:
arr1[:,:,1:2]

array([[[ 2],
        [ 5],
        [ 8]],

       [[14],
        [17],
        [20]]])

In [45]:
arr1[:,0:2,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[14, 15],
        [17, 18]]])

In [46]:
arr1[0,1,1]

5

In [47]:
arr1[:,1,1]

array([ 5, 17])