### number of approaches to create ndarray objects
1. array()
2. arange()
3. zeros()
4. ones()
5. full()
6. identity()
7. hstack() - horizontal stack
8. vstack() - vertical stack

random module

### 1) array()
=>   this function is used to convert traditional python objects into ndarray objects.

syntax:- varname =  numpy.array(object,dtype)

 Here:-

 varname = object of <class,ndarray>

 object = traditional python objects

 dtype = numpy data type e.g. int8,int16,int32,float16,float32,float64,...etc


In [1]:
import numpy as np

l1 = [10,20,30,40,50]
print(l1,type(l1))


[10, 20, 30, 40, 50] <class 'list'>


In [3]:
x = np.array(l1)
print(x,type(x))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [4]:
x.ndim

1

In [5]:
x.shape

(5,)

In [6]:
t=(10,20,30,40,50,60,70)
print(t,type(t))

(10, 20, 30, 40, 50, 60, 70) <class 'tuple'>


In [8]:
a= np.array(t)
print(a,type(a))

[10 20 30 40 50 60 70] <class 'numpy.ndarray'>


In [9]:
a.ndim

1

In [10]:
a.shape

(7,)

In [11]:
d1 = {10:1.2,20:3.4,30:5.6}
print(d1,type(d1))

{10: 1.2, 20: 3.4, 30: 5.6} <class 'dict'>


In [12]:
a= np.array(d1)

In [13]:
a

array({10: 1.2, 20: 3.4, 30: 5.6}, dtype=object)

In [14]:
print(a,type(a))

{10: 1.2, 20: 3.4, 30: 5.6} <class 'numpy.ndarray'>


In [15]:
t=(10,20,30,40,50,60)
a=np.array(t)
a

array([10, 20, 30, 40, 50, 60])

In [16]:
a.ndim

1

In [17]:
a.shape

(6,)

In [18]:
a.dtype

dtype('int64')

In [20]:
b= a.reshape(2,3)
b

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
c=a.reshape(3,2)

In [22]:
c

array([[10, 20],
       [30, 40],
       [50, 60]])

In [23]:
d = a.reshape(3,3)
d

ValueError: cannot reshape array of size 6 into shape (3,3)

In [24]:
b.ndim

2

In [25]:
c.ndim

2

In [26]:
b.shape

(2, 3)

In [27]:
c.shape

(3, 2)

In [29]:
t1= ((10,20),(30,40))
print(t1,type(t1))

((10, 20), (30, 40)) <class 'tuple'>


In [30]:
a = np.array(t1)
a

array([[10, 20],
       [30, 40]])

In [31]:
a.ndim

2

In [32]:
a.shape

(2, 2)

In [35]:
t2 = (((1,2,3),(4,5,6)),((10,20,30),(40,50,60)))
print(t2,type(t2))

(((1, 2, 3), (4, 5, 6)), ((10, 20, 30), (40, 50, 60))) <class 'tuple'>


In [36]:
y = np.array(t2)
print(y,type(y))

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]] <class 'numpy.ndarray'>


In [37]:
y.ndim

3

In [38]:
y.shape

(2, 2, 3)

In [40]:
b=y.reshape(6,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [41]:
b=y.reshape(4,3)

In [42]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [43]:
b.ndim

2

In [44]:
b.shape

(4, 3)

In [45]:
d = y.reshape(3,2,2)
d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [10, 20]],

       [[30, 40],
        [50, 60]]])

In [46]:
d.ndim

3

In [47]:
d[0]

array([[1, 2],
       [3, 4]])

In [48]:
d[1]

array([[ 5,  6],
       [10, 20]])

In [49]:
d[2]

array([[30, 40],
       [50, 60]])

In [52]:
d[0][0][1]

2