<a href="https://colab.research.google.com/github/DataZone123/numpy_yt/blob/main/NumPy_approaches.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Number of approaches to create an object of ndarray in numpy
=> We have 8 approaches to create an object of ndarray:-
1. array()
2. arange()
3. zeros()
4. ones()
5. full()
6. identity()
7. hstack()-- horizontal stack
8. vstack()-- vertical stack

Note:- There is one more way we can make ndarray object by using random module.

 ### 1) array()

=> This is a function used to convert Traditional Python Objects into ndarray objects.

=> syntax:-  varnamne = numpy.array(object,dtype)

Here,

varname = object of <class,ndarray>

object = traditional Python Object like-list,tuple,dict,etc

dtype = represents any numpy data type s.a. int8,int16,int32,float16,float32,float64,....etc.


In [ ]:
l1=[10,20,30,40,50,60]
print(l1,type(l1))

[10, 20, 30, 40, 50, 60] <class 'list'>


In [ ]:
import numpy as np
a= np.array(l1)
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [ ]:
a.dtype

dtype('int64')

In [ ]:
t=(10,20,30,40,50,60,70)
print(t,type(t))

(10, 20, 30, 40, 50, 60, 70) <class 'tuple'>


In [ ]:
a=np.array(t)
print(a,type(a))

[10 20 30 40 50 60 70] <class 'numpy.ndarray'>


In [ ]:
d1 = {10:1.2,20:3.4,30:4.5}
print(d1,type(d1))

{10: 1.2, 20: 3.4, 30: 4.5} <class 'dict'>


In [ ]:
a= np.array(d1)
print(a,type(a))

{10: 1.2, 20: 3.4, 30: 4.5} <class 'numpy.ndarray'>


In [ ]:
t = (10,20,30,40,50,60)
a=np.array(t)
a

array([10, 20, 30, 40, 50, 60])

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(6,)

In [ ]:
b = a.reshape(2,3) # factors of 6= 1,2,3,6

In [ ]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
b.shape

(2, 3)

In [ ]:
c = a.reshape(3,2)

In [ ]:
c

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
d = a.reshape(3,4)
d

ValueError: cannot reshape array of size 6 into shape (3,4)

In [ ]:
t1=((1,2),(3,4))
print(t1,type(t1))

((1, 2), (3, 4)) <class 'tuple'>


In [ ]:
a=np.array(t1)
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 2)

In [ ]:
x=a.reshape(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
x.ndim

2

In [ ]:
x=a.reshape(4,)
x

array([1, 2, 3, 4])

In [ ]:
x.ndim

1

## 3-d array

In [ ]:
t1 = (((1,2,1.5),(3,4,2.5)),((50,60,1.8),(70,80,3.4)))
print(t1,type(t1))

(((1, 2, 1.5), (3, 4, 2.5)), ((50, 60, 1.8), (70, 80, 3.4))) <class 'tuple'>


In [ ]:
a = np.array(t1)
print(a,type(a))

[[[ 1.   2.   1.5]
  [ 3.   4.   2.5]]

 [[50.  60.   1.8]
  [70.  80.   3.4]]] <class 'numpy.ndarray'>


In [ ]:
a.ndim

3

In [ ]:
a.shape

(2, 2, 3)

In [ ]:
b = a.reshape(2,6) # factors of 12= 1,2,3,4,6,12
b


array([[ 1. ,  2. ,  1.5,  3. ,  4. ,  2.5],
       [50. , 60. ,  1.8, 70. , 80. ,  3.4]])

In [ ]:
c = a.reshape(3,4)
c

array([[ 1. ,  2. ,  1.5,  3. ],
       [ 4. ,  2.5, 50. , 60. ],
       [ 1.8, 70. , 80. ,  3.4]])

In [ ]:
d= a.reshape(3,2,2)
d

array([[[ 1. ,  2. ],
        [ 1.5,  3. ]],

       [[ 4. ,  2.5],
        [50. , 60. ]],

       [[ 1.8, 70. ],
        [80. ,  3.4]]])

In [ ]:
d.ndim

3

In [ ]:
d[0]

array([[1. , 2. ],
       [1.5, 3. ]])

In [ ]:
d[0][0][1]

2.0

### 2) arange():

**Syntax1:-**  varname=numpy.arange(Value)

=>This creates an object of ndarray with the values from 0 to Value-1

**Syntax2:-**  varname=numpy.arange(Start,Stop)

=>This creates an object of ndarray with the values from Start to Stop-1

**Syntax3:-** varname=numpy.arange(Start,Stop,Step)

=>This creates an object of ndarray with the values from Start to Stop-1 with equal interval of Value-----step

    =>Here varname is an object of <class,ndarray>

**Note:-**

=>arange() always create an object of ndarray in 1-D array only but not Possible to create directly 2-D and Multi Dimesional Arrays.

=>To create 2-D and Multi Dimesional Arrays, we must use reshape() or shape attribute.

In [ ]:
a=range(5)
a

range(0, 5)

In [ ]:
for val in a:
  print(val)

0
1
2
3
4


In [ ]:
for val in range(5,10):
  print(val)

5
6
7
8
9


In [ ]:
for val in range(10,22,2):
  print(val)

10
12
14
16
18
20


In [ ]:
import numpy as np
a= np.arange(5)

In [ ]:
print(a,type(a))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
a.ndim

1

In [ ]:
a.shape


(5,)

In [ ]:
# Syntax2:- varname=numpy.arange(Start,Stop)

a= np.arange(10,20)
print(a,type(a))

[10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>


In [ ]:
a.ndim


1

In [ ]:
# Syntax3:- varname=numpy.arange(Start,Stop,Step)

a= np.arange(10,22,2)
print(a,type(a))

[10 12 14 16 18 20] <class 'numpy.ndarray'>


In [ ]:
a.ndim

1

In [ ]:
a.shape

(6,)

In [ ]:
b=a.reshape(2,3)
b

array([[10, 12, 14],
       [16, 18, 20]])

In [ ]:
c=a.reshape(3,2)
c

array([[10, 12],
       [14, 16],
       [18, 20]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
c.ndim

2

In [ ]:
c.shape

(3, 2)

In [ ]:
l1=[10,20,30,40]
l1

[10, 20, 30, 40]

In [ ]:
a=np.arange(l1)
a

TypeError: unsupported operand type(s) for -: 'list' and 'int'

### 3) zeros():

=> This function is used to create ZERO matrix of 1-D,2-D,or n-D

=> syntax:- varname=numpy.zeros(shape,dtype)

=> shape can be 1-D(number of zeros),2-D(Rows,columns),n-D(number of matrices,rows,columns)


In [28]:
import numpy as np
a=np.zeros(12)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
a.dtype

dtype('float64')

In [30]:
a=np.zeros(12,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
a.dtype

dtype('int64')

In [32]:
a.reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
a.reshape(6,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [34]:
a.reshape(3,2,2)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [35]:
a=np.zeros(shape=(3,4,5),dtype=int)
a

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [36]:
a.ndim

3

In [38]:
d = np.zeros((3,2,2),int)
d

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

### 4) ones():

=> This function is used to create ONE's matrix of 1-D,2-D,or n-D

=> syntax:- varname=numpy.ones(shape,dtype)

=> shape can be 1-D(number of ones),2-D(Rows,columns),n-D(number of matrices,rows,columns)

In [21]:
import numpy as np
a=np.ones(10)
print(a,type(a))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [22]:
a=np.ones(10,dtype=int)
print(a,type(a))

[1 1 1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>


In [24]:
a.dtype

dtype('int64')

In [26]:
a = np.ones(shape=(3,3,4),dtype=int)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])